---
info:
  title: Meterpreter Deps
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/meterpreter-deps
  x-cortex-tag: meterpreter-deps
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
